### PR TITLE
Cleanup Refactor

### PR DESCRIPTION
**Pull request by andrewvc**
This is a significant refactor that alters the internal design to achieve the following:

1. Fast again (actually, faster than before!) by using an internal queue and bulk ACKs. 
2. Shutdown cleanly
3. Make metadata optional (important for perf).

### CODE REVIEW

**Comment by andrewvc** [comment]
Perf benchmarks (using ` bin/logstash -e "input { generator {} } output { rabbitmq { host => localhost exchange => ptest exchange_type => fanout durable => false} }"` to generate load)

```
# new code, no metadata
~/D/ls2.2rmq $ bin/logstash -e "input { rabbitmq { host => localhost exchange => ptest exchange_type => fanout auto_delete => true prefetch_count => 2048 } } output { stdout { } }" | pv -l | wc -l
^C96k 0:00:30 [14.6k/s]
# new code, with metadata
~/D/ls2.2rmq $ bin/logstash -e "input { rabbitmq { metadata_enabled => true host => localhost exchange => ptest exchange_type => fanout auto_delete => true prefetch_count => 2048 } } output { stdout { } }" | pv -l | wc -l
 116k 0:00:35 [6.61k/s]

# old code, no metadata (3.1.3)
~/D/logstash-2.2.2 $ bin/logstash -e "input { rabbitmq { host => localhost exchange => ptest auto_delete => true prefetch_count => 2048 } } output { stdout { } }"  | pv -l | wc -l
 185k 0:00:30 [11.7k/s]
```

**Comment by andrewvc** [comment]
@michaelklishin what are your thoughts on the optimization here with `@hare_info.channel.ack(last_delivery_tag, true) if @ack` to acknowledge batches of messages?

**Comment by talevy** [comment]
LGTM

**Comment by ph** [comment]
Just revert to this.
`s.add_runtime_dependency "logstash-core", ">= 2.0.0", "< 3.0.0"`

**Pull request closed without merging**
