### PR TITLE
Set default codec to JSON

### PR DESCRIPTION
**Pull request by andrewvc**
This was the old behavior and was only changed by accident.

### CODE REVIEW

**Comment by ph** [comment]
Should we have a test for this?

**Comment by andrewvc** [comment]
@ph yes we should!

**Comment by andrewvc** [comment]
@ph test added!

**Comment by ph** [comment]
jenkins, test it

**Comment by andrewvc** [comment]
@ph looks like the specs are passing!

**Comment by ph** [comment]
LGTM :)

**Pull request merged**
