### PR TITLE
migrate https://github.com/elasticsearch/logstash/pull/1100

### PR DESCRIPTION
**Pull request by suyograo**
From @ekimekim

### CODE REVIEW

**Comment by electrical** [comment]
LGTM

**Comment by suyograo** [comment]
@ekimekim can you please perform step 2 of https://github.com/elasticsearch/logstash/blob/master/CONTRIBUTING.md#contribution-steps

**Comment by ekimekim** [comment]
Done.

**Comment by jsvd** [comment]
@ekimekim strange, we're getting a failed check on the cla, did you sign it with the same email used in the commit?

**Comment by ekimekim** [comment]
Ah, my mistake. Forgot that it was committed with my work email.

**Comment by ekimekim** [comment]
Done.

**Comment by jsvd** [comment]
Still no :( Strangely, from what I see, the commit was recorded as from `ekimekim <noreply@example.com>`:

https://github.com/logstash-plugins/logstash-input-rabbitmq/pull/11.patch

That's why the CLA is not working. can you maybe reopen the pr w/ the correct email? Sorry about the trouble.

**Comment by ekimekim** [comment]
Very strange...perhaps something went wrong during the migration process.
I opened a new PR: https://github.com/logstash-plugins/logstash-input-rabbitmq/pull/15

**Comment by jsvd** [comment]
closed as a dup of #15

**Pull request closed without merging**
